### PR TITLE
Add translator

### PR DESCRIPTION
**Pull request by vr8hub**
Just to document everything: I found 1884 and 1886 scans on archive.org published by Vizetelly & Co. Unlike Orcival, the translations both matched the one Gutenberg used, so it should be safe to use them as the translator for this production.

### CODE REVIEW

**Comment by acabal** [comment]
But, can we render it as "Vizetelly and Company" instead of "Vizetelly & Co."?  We already have an item in the catalog under "Vizetelly and Company".

**Comment by vr8hub** [comment]
I know that by "we" you did not mean "me," after spending two days researching all this and showing you the documentation for why it's Vizatelly & Co. and making the changes and having to fiddle around with the ampersands. I just know it.

:)

Further, this is from the titlepage of Lerouge.
<picture redacted by github; I sent it to the group>

So I'm going to respectfully say if you want them to be the same, you need to change the other one. :)

**Comment by acabal** [comment]
Vizetelly and Company was *already* in the metadata, there was very little that had to be done here; and they mean the same thing. But nevertheless, I will do this for you.

**Comment by vr8hub** [comment]
Yes, and I demonstrated pretty conclusively, in two different ways, why it should be Vizetelly & Co. instead, and I told you that's what I was using. Changing the name was the trivial part of the work to get everything done for adding the translator, so I would also argue with "very little … had to be done".

But let's don't. I did what you asked me to do — I researched it, I identified the translator, I confirmed that with scans, and I made the changes, just like I did for the other four books. And in response, you asked me to change what I did just because something else uses something different. (Possibly in error as well, but, as I demonstrated, it's entirely possible that, depending on dates, "Vizetelly and Company" is correct for the other book, and thus they should be different.)

At the end of the day, if you want Lerouge to use Vizetelly and Company, you are free to change it. You are the boss. But if you do, or you don't, you're not doing anything for me. You're doing it for the same reason I did the work I did—for the project.

**Comment by acabal** [comment]
Vince, I get enough of this kind of interpersonal style in my day job, for which at least I get paid. I don't need it in my hobby life. Let's take a break for a while.

**Pull request merged**
